const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const DB='CF_OT_V1', COUNTER='CF_OT_COUNTER_V1'; let data=null, timer=null;
const IDB_NAME='CF_OT_DB_V2',IDB_STORE='orders';
const SUPABASE_URL='https://hypzysgjpsgmzkztytsq.supabase.co';
const SUPABASE_KEY='sb_publishable_8Ql_sMjbEAuYwbyoBQzZIA_LS7fJOq7';
async function cloudRequest(path,options={}){const headers={apikey:SUPABASE_KEY,Authorization:'Bearer '+SUPABASE_KEY,'Content-Type':'application/json',...(options.headers||{})};const r=await fetch(SUPABASE_URL+'/rest/v1/'+path,{...options,headers});if(!r.ok)throw new Error('Supabase '+r.status+': '+await r.text());if(r.status===204)return null;const t=await r.text();return t?JSON.parse(t):null}
async function cloudPut(order){return cloudRequest('ordenes_trabajo?on_conflict=ot',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({ot:order.ot,datos:order,actualizado_en:new Date().toISOString()})})}
async function cloudGet(ot){const a=await cloudRequest('ordenes_trabajo?ot=eq.'+encodeURIComponent(ot)+'&select=datos&limit=1');return a?.[0]?.datos||null}
async function cloudList(){const a=await cloudRequest('ordenes_trabajo?select=ot,datos,actualizado_en&order=actualizado_en.desc');return a||[]}
async function cloudDelete(ot){return cloudRequest('ordenes_trabajo?ot=eq.'+encodeURIComponent(ot),{method:'DELETE',headers:{Prefer:'return=minimal'}})}
async function syncLocalToCloud(){let db={};try{db=JSON.parse(localStorage.getItem(DB)||'{}')}catch(e){}for(const x of Object.values(db)){try{const full=await idbGet(x.ot)||x;await cloudPut(full)}catch(e){console.warn('Sincronización pendiente',x.ot,e)}}}
function idbOpen(){return new Promise((resolve,reject)=>{const r=indexedDB.open(IDB_NAME,1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(IDB_STORE))db.createObjectStore(IDB_STORE,{keyPath:'ot'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function idbPut(order){const db=await idbOpen();return await new Promise((resolve,reject)=>{const tx=db.transaction(IDB_STORE,'readwrite');tx.objectStore(IDB_STORE).put(JSON.parse(JSON.stringify(order)));tx.oncomplete=()=>{db.close();resolve(true)};tx.onerror=()=>{db.close();reject(tx.error)}})}
async function idbGet(ot){const db=await idbOpen();return await new Promise((resolve,reject)=>{const tx=db.transaction(IDB_STORE,'readonly'),r=tx.objectStore(IDB_STORE).get(ot);r.onsuccess=()=>{db.close();resolve(r.result||null)};r.onerror=()=>{db.close();reject(r.error)}})}
async function idbDelete(ot){const db=await idbOpen();return await new Promise((resolve,reject)=>{const tx=db.transaction(IDB_STORE,'readwrite');tx.objectStore(IDB_STORE).delete(ot);tx.oncomplete=()=>{db.close();resolve(true)};tx.onerror=()=>{db.close();reject(tx.error)}})}
function liteOrder(order){const x=JSON.parse(JSON.stringify(order));x.photos=[];(x.hallazgos||[]).forEach(h=>h.photos=[]);if(x.aceptacion)x.aceptacion.firma='';return x}
async function migrateLegacy(){let db={};try{db=JSON.parse(localStorage.getItem(DB)||'{}')}catch(e){}for(const x of Object.values(db)){try{const old=await idbGet(x.ot);if(!old)await idbPut(x)}catch(e){console.error('Migración OT',x.ot,e)}}}
const ids=['cliente','rut','telefono','email','marca','modelo','ano','patente','vin','km','bencina','solicitados','conclusiones','obs','estado'];
const today=()=>{const d=new Date(),p=n=>String(n).padStart(2,'0');return p(d.getDate())+'/'+p(d.getMonth()+1)+'/'+d.getFullYear()};
const money=n=>'$'+Math.round(Number(n)||0).toLocaleString('es-CL');
function nextNumber(){let n=Number(localStorage.getItem(COUNTER)||0)+1;localStorage.setItem(COUNTER,n);return 'OT-'+String(n).padStart(6,'0')}
function fresh(){return{ot:nextNumber(),fecha:today(),estado:'Recepcionado',photos:[],hallazgos:[],items:[],cliente:'',rut:'',telefono:'',email:'',marca:'',modelo:'',ano:'',patente:'',vin:'',km:'',bencina:'1/2',solicitados:'',conclusiones:'',obs:'',aceptacion:{nombre:'',rut:'',aceptado:false,fechaHora:'',firma:''}}}
function collect(){ids.forEach(id=>data[id]=$('#'+id).value)}
function schedule(){clearTimeout(timer);timer=setTimeout(save,350)}
async function save(){if(!data)return false;collect();try{await idbPut(data);const db=JSON.parse(localStorage.getItem(DB)||'{}'),lite=liteOrder(data);db[data.ot]=lite;localStorage.setItem(DB,JSON.stringify(db));localStorage.setItem('CF_OT_ACTIVE',data.ot);$('#otBadge').textContent=data.ot;try{await cloudPut(data)}catch(e){console.warn('Guardado local OK; nube pendiente',e)}return true}catch(e){console.error(e);alert('No se pudo guardar la OT en el historial del dispositivo. Los datos siguen abiertos en pantalla.');return false}}
function fill(){ $('#ot').value=data.ot;$('#fecha').value=data.fecha;ids.forEach(id=>$('#'+id).value=data[id]??'');data.aceptacion=data.aceptacion||{nombre:'',rut:'',aceptado:false,fechaHora:'',firma:''};$('#aceptaNombre').value=data.aceptacion.nombre||data.cliente||'';$('#aceptaRut').value=data.aceptacion.rut||data.rut||'';$('#aceptaCheck').checked=!!data.aceptacion.aceptado;updateAcceptStamp();renderPhotos();renderHallazgos();renderItems();$('#otBadge').textContent=data.ot;setTimeout(drawSavedSignature,0)}
async function newOT(){if(data)await save();data=fresh();fill();await save()}
ids.forEach(id=>$('#'+id).addEventListener('input',schedule));
function compress(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{let w=im.width,h=im.height,m=1100;if(Math.max(w,h)>m){let q=m/Math.max(w,h);w*=q;h*=q}let c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(im,0,0,w,h);res(c.toDataURL('image/jpeg',.68))};im.onerror=rej;im.src=r.result};r.onerror=rej;r.readAsDataURL(file)})}
async function addPhotos(files){for(const f of files){try{data.photos.push(await compress(f))}catch(e){alert('No se pudo cargar '+f.name)}}renderPhotos();save()}
$('#camera').onchange=e=>addPhotos(e.target.files);$('#gallery').onchange=e=>addPhotos(e.target.files);
function renderPhotos(){$('#photos').innerHTML='';data.photos.forEach((src,i)=>{let d=document.createElement('div');d.className='photo';d.innerHTML=`<img src="${src}"><button>✕</button>`;d.querySelector('button').onclick=()=>{data.photos.splice(i,1);renderPhotos();save()};$('#photos').append(d)});$('#photoCount').textContent=data.photos.length+' foto'+(data.photos.length===1?'':'s')+(data.photos.length<6?' · faltan '+(6-data.photos.length)+' para 6':' · ✓ registro mínimo completo')}
function addHallazgo(){data.hallazgos.push({texto:'',informado:false,autorizacion:'Pendiente',photos:[]});renderHallazgos();save()}
async function addHallazgoPhotos(i,files){let h=data.hallazgos[i];h.photos=h.photos||[];for(const f of files){try{h.photos.push(await compress(f))}catch(e){alert('No se pudo cargar '+f.name)}}renderHallazgos();save()}
function renderHallazgos(){$('#hallazgos').innerHTML='';data.hallazgos.forEach((h,i)=>{h.photos=h.photos||[];let d=document.createElement('div');d.className='hallazgo';d.innerHTML=`<textarea rows="3" placeholder="Detalle del hallazgo...">${h.texto||''}</textarea><div class="checks"><label><input type="checkbox" ${h.informado?'checked':''}> Informado al cliente</label><label>Autorización <select><option>Pendiente</option><option>Autorizado</option><option>No autorizado</option></select></label></div><div class="photoBtns"><label class="btn mini">📷 Evidencia<input class="hcam" type="file" accept="image/*" capture="environment" hidden></label><label class="btn secondary mini">🖼️ Galería<input class="hgal" type="file" accept="image/*,.jpg,.jpeg,.png,.webp,.heic,.heif" multiple hidden></label></div><div class="photos hphotos"></div><button class="delHall">Eliminar hallazgo</button>`;let ta=d.querySelector('textarea'),ch=d.querySelector('.checks input'),sel=d.querySelector('select');sel.value=h.autorizacion;ta.oninput=()=>{h.texto=ta.value;schedule()};ch.onchange=()=>{h.informado=ch.checked;save()};sel.onchange=()=>{h.autorizacion=sel.value;save()};d.querySelector('.hcam').onchange=e=>addHallazgoPhotos(i,e.target.files);d.querySelector('.hgal').onchange=e=>addHallazgoPhotos(i,e.target.files);let ph=d.querySelector('.hphotos');h.photos.forEach((src,j)=>{let p=document.createElement('div');p.className='photo';p.innerHTML=`<img src="${src}"><button>✕</button>`;p.querySelector('button').onclick=()=>{h.photos.splice(j,1);renderHallazgos();save()};ph.append(p)});d.querySelector('.delHall').onclick=()=>{data.hallazgos.splice(i,1);renderHallazgos();save()};$('#hallazgos').append(d)})}
$('#addHallazgo').onclick=addHallazgo;
function addItem(){data.items.push({tipo:'Repuesto',desc:'',cant:1,unit:0});renderItems();save()}
function renderItems(){let b=$('#items');b.innerHTML='';let total=0;data.items.forEach((it,i)=>{let tr=document.createElement('tr'),t=(Number(it.cant)||0)*(Number(it.unit)||0);total+=t;tr.innerHTML=`<td><select><option>Repuesto</option><option>Insumo</option><option>Mano de obra</option></select></td><td><input value="${esc(it.desc)}"></td><td><input inputmode="decimal" value="${it.cant}"></td><td><input inputmode="numeric" value="${it.unit}"></td><td><b>${money(t)}</b></td><td><button>✕</button></td>`;let a=tr.querySelectorAll('select,input');a[0].value=it.tipo;a[0].onchange=()=>{it.tipo=a[0].value;save()};a[1].oninput=()=>{it.desc=a[1].value;schedule()};a[2].oninput=()=>{it.cant=a[2].value;updateTotals();schedule()};a[2].onblur=renderItems;a[3].oninput=()=>{it.unit=a[3].value;updateTotals();schedule()};a[3].onblur=renderItems;tr.querySelector('button').onclick=()=>{data.items.splice(i,1);renderItems();save()};b.append(tr)});updateTotals()}
function updateTotals(){const neto=data.items.reduce((s,it)=>s+(Number(it.cant)||0)*(Number(it.unit)||0),0);$('#netoTotal').textContent=money(neto);const iva=Math.round(neto*.19);$('#ivaTotal').textContent=money(iva);$('#granTotal').textContent=money(neto+iva)}
function esc(s){return String(s||'').replace(/"/g,'&quot;')}
$('#addItem').onclick=addItem;$('#save').onclick=async()=>{if(await save())alert('OT guardada en el historial del dispositivo.')}
$('#newOT').onclick=()=>{if(confirm('¿Crear una nueva Orden de Trabajo?'))newOT()};
$('#history').onclick=async()=>{await save();let rows=[];try{rows=await cloudList()}catch(e){console.warn('Historial nube no disponible',e);let db={};try{db=JSON.parse(localStorage.getItem(DB)||'{}')}catch(_e){}rows=Object.values(db).reverse().map(datos=>({ot:datos.ot,datos}))}let list=$('#histList');list.innerHTML='';rows.forEach(row=>{let x=row.datos||row,d=document.createElement('div');d.className='histRow';d.innerHTML=`<div class="histOpen"><b>${x.ot}</b> · ${x.fecha}<br>${x.patente||'Sin patente'} · ${x.marca||''} ${x.modelo||''}<br><small>${x.cliente||'Sin cliente'} · ${x.estado}</small></div><button class="histDelete" type="button">Eliminar</button>`;d.querySelector('.histOpen').onclick=async()=>{try{data=await cloudGet(x.ot)||await idbGet(x.ot)||x}catch(e){console.error(e);data=x}await idbPut(data);localStorage.setItem('CF_OT_ACTIVE',x.ot);fill();$('#histDlg').close()};d.querySelector('.histDelete').onclick=async e=>{e.stopPropagation();if(!confirm('¿Eliminar definitivamente '+x.ot+' del historial compartido?'))return;try{await cloudDelete(x.ot);await idbDelete(x.ot)}catch(err){console.error(err);alert('No se pudo eliminar la OT.');return}let db={};try{db=JSON.parse(localStorage.getItem(DB)||'{}')}catch(_e){}delete db[x.ot];localStorage.setItem(DB,JSON.stringify(db));if(localStorage.getItem('CF_OT_ACTIVE')===x.ot)localStorage.removeItem('CF_OT_ACTIVE');d.remove()};list.append(d)});$('#histDlg').showModal()};$('#closeHist').onclick=()=>$('#histDlg').close();
const firma=$('#firma'),fctx=firma.getContext('2d');let drawing=false;
function firmaPos(e){const r=firma.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return{x:(p.clientX-r.left)*firma.width/r.width,y:(p.clientY-r.top)*firma.height/r.height}}
function startFirma(e){e.preventDefault();drawing=true;let p=firmaPos(e);fctx.beginPath();fctx.moveTo(p.x,p.y)}
function moveFirma(e){if(!drawing)return;e.preventDefault();let p=firmaPos(e);fctx.lineWidth=4;fctx.lineCap='round';fctx.strokeStyle='#111';fctx.lineTo(p.x,p.y);fctx.stroke()}
function endFirma(){if(!drawing)return;drawing=false;data.aceptacion.firma=firma.toDataURL('image/png');save()}
firma.addEventListener('pointerdown',startFirma);firma.addEventListener('pointermove',moveFirma);window.addEventListener('pointerup',endFirma);
function drawSavedSignature(){fctx.clearRect(0,0,firma.width,firma.height);if(data?.aceptacion?.firma){let im=new Image();im.onload=()=>fctx.drawImage(im,0,0,firma.width,firma.height);im.src=data.aceptacion.firma}}
function updateAcceptStamp(){let a=data.aceptacion||{};$('#acceptStamp').textContent=a.aceptado?('Aceptada · '+a.fechaHora):'Pendiente de aceptación';$('#acceptStamp').classList.toggle('ok',!!a.aceptado)}
$('#aceptaNombre').oninput=()=>{data.aceptacion.nombre=$('#aceptaNombre').value;schedule()};$('#aceptaRut').oninput=()=>{data.aceptacion.rut=$('#aceptaRut').value;schedule()};
$('#aceptaCheck').onchange=()=>{data.aceptacion.aceptado=$('#aceptaCheck').checked;if(!data.aceptacion.aceptado)data.aceptacion.fechaHora='';save();updateAcceptStamp()};
$('#clearFirma').onclick=()=>{fctx.clearRect(0,0,firma.width,firma.height);data.aceptacion.firma='';save()};
$('#confirmAcepta').onclick=()=>{data.aceptacion.nombre=$('#aceptaNombre').value.trim();data.aceptacion.rut=$('#aceptaRut').value.trim();if(!data.aceptacion.nombre||!data.aceptacion.rut){alert('Completa nombre y RUT de quien acepta.');return}if(!data.aceptacion.firma){alert('Falta la firma del cliente.');return}$('#aceptaCheck').checked=true;data.aceptacion.aceptado=true;data.aceptacion.fechaHora=new Date().toLocaleString('es-CL');save();updateAcceptStamp();alert('Aceptación registrada en la OT.')};
function pdfHeader(doc,title){doc.setFillColor(10,10,10);doc.rect(0,0,210,28,'F');doc.setTextColor(255);doc.setFontSize(22);doc.setFont('helvetica','bold');doc.text('CERO FALLA',15,14);doc.setFontSize(9);doc.text('ESPECIALISTA AUTOMOTRIZ',15,21);doc.text(data.ot+'  |  '+data.fecha,145,16);doc.setTextColor(0);doc.setFontSize(16);doc.text(title,15,38)}
function openPdf(doc){const blob=doc.output('blob'),url=URL.createObjectURL(blob);let w=window.open(url,'_blank');if(!w){const a=document.createElement('a');a.href=url;a.target='_blank';a.click()}setTimeout(()=>URL.revokeObjectURL(url),60000)}
function makeOtPdf(){save();const {jsPDF}=window.jspdf,doc=new jsPDF(),L=15,W=180;pdfHeader(doc,'ORDEN DE TRABAJO');let y=47;
const line=(txt,size=10,bold=false)=>{doc.setFont('helvetica',bold?'bold':'normal');doc.setFontSize(size);let a=doc.splitTextToSize(String(txt||''),W);if(y+a.length*5>282){doc.addPage();y=16}doc.text(a,L,y);y+=a.length*5+2};
line('Estado: '+data.estado,10,true);line('CLIENTE',12,true);line(`${data.cliente} | RUT: ${data.rut} | Tel: ${data.telefono} | ${data.email}`);line('VEHÍCULO',12,true);line(`${data.marca} ${data.modelo} ${data.ano} | Patente: ${data.patente} | VIN: ${data.vin} | Km: ${data.km} | Combustible: ${data.bencina}`);
if(data.photos.length){line('FOTOS DE RECEPCIÓN',12,true);for(let i=0;i<data.photos.length;i++){if(y+58>280){doc.addPage();y=16}try{doc.addImage(data.photos[i],'JPEG',15,y,82,55);if(i+1<data.photos.length)doc.addImage(data.photos[++i],'JPEG',105,y,82,55);y+=60}catch(e){}}}
line('TRABAJOS SOLICITADOS POR EL CLIENTE',12,true);line(data.solicitados||'Sin detalle.');
if(data.hallazgos.length){line('HALLAZGOS / TRABAJOS ADICIONALES',12,true);data.hallazgos.forEach((h,i)=>{line(`${i+1}. ${h.texto||''} | ${h.informado?'Informado':'No informado'} | ${h.autorizacion}`);for(const src of (h.photos||[])){if(y+58>280){doc.addPage();y=16}try{doc.addImage(src,'JPEG',15,y,82,55);y+=60}catch(e){}}})}
line('CONCLUSIONES',12,true);line(data.conclusiones||'Sin detalle.');
if(data.aceptacion?.aceptado){line('ACEPTACIÓN DEL CLIENTE',12,true);line(`Aceptada por: ${data.aceptacion.nombre} | RUT: ${data.aceptacion.rut} | Fecha y hora: ${data.aceptacion.fechaHora}`);line('Declara haber recibido la información de esta Orden de Trabajo y autoriza los trabajos indicados como aceptados.');if(data.aceptacion.firma){if(y+38>280){doc.addPage();y=16}try{doc.addImage(data.aceptacion.firma,'PNG',15,y,70,28);y+=34}catch(e){}}}
if(data.obs){line('OBSERVACIONES FINALES',12,true);line(data.obs)}return doc}
function makeCuentaPdf(){save();const {jsPDF}=window.jspdf,doc=new jsPDF(),L=14,R=196;pdfHeader(doc,'LIQUIDACIÓN');let y=49;
const txt=(s,x,yy,size=11,bold=false,align='left')=>{doc.setFont('helvetica',bold?'bold':'normal');doc.setFontSize(size);doc.text(String(s||''),x,yy,{align})};
const rule=()=>{doc.setDrawColor(190);doc.line(L,y,R,y);y+=5};
txt('CLIENTE',L,y,12,true);y+=6;txt(data.cliente||'Sin nombre',L,y,11,true);y+=5;txt(`RUT: ${data.rut||'-'}   Tel: ${data.telefono||'-'}   Email: ${data.email||'-'}`,L,y,10);y+=8;
txt('VEHÍCULO',L,y,12,true);y+=6;txt(`${data.marca||''} ${data.modelo||''} ${data.ano||''}   Patente: ${data.patente||'-'}`,L,y,11,true);y+=5;txt(`VIN: ${data.vin||'-'}   Km: ${data.km||'-'}`,L,y,10);y+=8;rule();
const x=[L,38,111,130,158,R];txt('TIPO',x[0],y,10,true);txt('DESCRIPCIÓN',x[1],y,10,true);txt('CANT.',x[2],y,10,true,'right');txt('UNITARIO',x[4],y,10,true,'right');txt('NETO',x[5],y,10,true,'right');y+=4;rule();
let neto=0;
if(!data.items.length){txt('Sin ítems cargados.',L,y,11);y+=7}
data.items.forEach(it=>{let t=(+it.cant||0)*(+it.unit||0);neto+=t;if(y>265){doc.addPage();y=20}let desc=doc.splitTextToSize(String(it.desc||''),68),h=Math.max(7,desc.length*5);txt(it.tipo,L,y,10);doc.setFont('helvetica','normal');doc.setFontSize(10);doc.text(desc,x[1],y);txt(it.cant,x[2],y,10,false,'right');txt(money(it.unit),x[4],y,10,false,'right');txt(money(t),x[5],y,10,true,'right');y+=h;doc.setDrawColor(225);doc.line(L,y-2,R,y-2)});
y+=5;const iva=Math.round(neto*.19);txt('Neto total',150,y,11,true,'right');txt(money(neto),R,y,11,true,'right');y+=7;txt('IVA 19%',150,y,11,true,'right');txt(money(iva),R,y,11,true,'right');y+=7;doc.setDrawColor(190,20,28);doc.line(130,y-4,R,y-4);txt('TOTAL',150,y,15,true,'right');txt(money(neto+iva),R,y,15,true,'right');
doc.setFont('helvetica','normal');doc.setFontSize(10);doc.setTextColor(80);doc.text('Cero Falla · +56 9 6915 2515 · cerofalla.automotriz@gmail.com',105,289,{align:'center'});doc.setTextColor(0);return doc}
$('#pdf').onclick=()=>{try{openPdf(makeOtPdf())}catch(e){console.error(e);alert('No se pudo generar el informe OT. '+e.message)}};
$('#cuentaPdf').onclick=()=>{try{openPdf(makeCuentaPdf())}catch(e){console.error(e);alert('No se pudo generar la cuenta. '+e.message)}};
(async()=>{await migrateLegacy();await syncLocalToCloud();const active=localStorage.getItem('CF_OT_ACTIVE');if(active){try{data=await cloudGet(active)||await idbGet(active)}catch(e){console.error(e);try{data=await idbGet(active)}catch(_e){}}}if(!data){let db={};try{db=JSON.parse(localStorage.getItem(DB)||'{}')}catch(e){};if(active&&db[active])data=db[active]}if(!data)data=fresh();fill();if(!active)await save()})();