const $=s=>document.querySelector(s),fields=['fecha','vigencia','estado','condiciones','cliente','rut','telefono','email','marca','modelo','ano','patente','vin','km','notas'],STORE='CF_COT_PREVIEW_V1',COUNT='CF_COT_PREVIEW_COUNT';let current=null;
const money=n=>'$'+Math.round(Number(n)||0).toLocaleString('es-CL');
const iso=d=>{let z=new Date(d);return z.toISOString().slice(0,10)};
function all(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch{return {}}}
function persist(){const a=all();a[current.numero]=current;localStorage.setItem(STORE,JSON.stringify(a))}
function fresh(){const n=Number(localStorage.getItem(COUNT)||0)+1;localStorage.setItem(COUNT,n);const d=new Date();return {numero:'COT-'+String(n).padStart(6,'0'),fecha:iso(d),vigencia:iso(d.getTime()+15*86400000),estado:'Borrador',items:[],condiciones:'',cliente:'',rut:'',telefono:'',email:'',marca:'',modelo:'',ano:'',patente:'',vin:'',km:'',notas:''}}
function load(o){current=structuredClone(o);$('#numero').value=current.numero;$('#numeroBadge').textContent=current.numero;fields.forEach(k=>$('#'+k).value=current[k]||'');render()}
function collect(){fields.forEach(k=>current[k]=$('#'+k).value)}
function save(){collect();persist();$('#numeroBadge').textContent=current.numero}
function totals(){const neto=current.items.reduce((s,i)=>s+(Number(i.cant)||0)*(Number(i.unit)||0),0);$('#neto').textContent=money(neto);$('#iva').textContent=money(Math.round(neto*.19));$('#total').textContent=money(neto+Math.round(neto*.19));return neto}
function render(){const body=$('#items');body.innerHTML='';current.items.forEach((it,i)=>{const tr=document.createElement('tr');const cells=[];for(let j=0;j<7;j++){const td=document.createElement('td');tr.append(td);cells.push(td)}const tipo=document.createElement('select');['Repuesto','Mano de obra','Insumo'].forEach(v=>tipo.add(new Option(v,v)));tipo.value=it.tipo;cells[0].append(tipo);const cat=document.createElement('select');['Original','OEM','Alternativo'].forEach(v=>cat.add(new Option(v,v)));cat.value=it.categoria||'Original';cat.disabled=it.tipo!=='Repuesto';cells[1].append(cat);const inp=(cell,val,mode)=>{const x=document.createElement('input');x.value=val;if(mode)x.inputMode=mode;cell.append(x);return x};const desc=inp(cells[2],it.desc||'');const cant=inp(cells[3],it.cant,'decimal');const unit=inp(cells[4],it.unit,'numeric');const net=document.createElement('strong');cells[5].append(net);const del=document.createElement('button');del.textContent='✕';cells[6].append(del);const refresh=()=>{net.textContent=money((Number(it.cant)||0)*(Number(it.unit)||0));totals()};tipo.onchange=()=>{it.tipo=tipo.value;cat.disabled=it.tipo!=='Repuesto';save()};cat.onchange=()=>{it.categoria=cat.value;save()};desc.oninput=()=>{it.desc=desc.value;save()};cant.oninput=()=>{it.cant=cant.value;refresh();save()};unit.oninput=()=>{it.unit=unit.value;refresh();save()};del.onclick=()=>{current.items.splice(i,1);render();save()};body.append(tr);refresh()});totals()}
$('#agregar').onclick=()=>{current.items.push({tipo:'Repuesto',categoria:'Original',desc:'',cant:1,unit:0});render();save()};
fields.forEach(k=>$('#'+k).addEventListener('input',save));
$('#guardar').onclick=()=>{save();alert('Cotización guardada en el historial de prueba de este dispositivo.')};
$('#nuevo').onclick=()=>{if(!confirm('¿Crear nueva cotización?'))return;save();load(fresh());save()};
$('#historial').onclick=()=>{save();$('#histList').innerHTML='';Object.values(all()).reverse().forEach(o=>{const el=document.createElement('div');el.className='histRow';el.textContent=o.numero+' · '+(o.cliente||'Sin cliente')+' · '+(o.patente||'Sin patente')+' · '+o.estado;el.onclick=()=>{load(o);$('#histDlg').close()};$('#histList').append(el)});$('#histDlg').showModal()};
$('#cerrar').onclick=()=>$('#histDlg').close();
function pdf(){save();const {jsPDF}=window.jspdf,doc=new jsPDF(),W=210;let y=48;const tx=(v,x,yy,size=9,bold=false,align='left')=>{doc.setFont('helvetica',bold?'bold':'normal');doc.setFontSize(size);doc.setTextColor(25);doc.text(String(v||'-'),x,yy,{align})};const header=()=>{doc.setFillColor(12,13,16);doc.rect(0,0,W,30,'F');doc.setFillColor(205,24,34);doc.rect(0,30,W,2,'F');doc.setTextColor(255);doc.setFont('helvetica','bold');doc.setFontSize(21);doc.text('CERO FALLA',14,14);doc.setFontSize(8);doc.text('ESPECIALISTA AUTOMOTRIZ',14,21);doc.text(current.numero,196,14,{align:'right'});doc.setTextColor(25);tx('COTIZACIÓN',14,41,16,true)};const page=()=>{doc.addPage();header();y=49};const ensure=h=>{if(y+h>271)page()};const section=t=>{ensure(15);doc.setFillColor(24,26,30);doc.roundedRect(14,y,182,9,1,1,'F');doc.setFillColor(205,24,34);doc.rect(14,y,3,9,'F');doc.setTextColor(255);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text(t,20,y+6);y+=15};const wrap=(s,x,max)=>{doc.setFont('helvetica','normal');doc.setFontSize(9);return doc.splitTextToSize(String(s||'-'),max)};header();tx('Fecha: '+current.fecha,14,y);tx('Válida hasta: '+current.vigencia,196,y,9,false,'right');y+=9;
section('CLIENTE Y VEHÍCULO');const pairs=[['Cliente',current.cliente,'Vehículo',[current.marca,current.modelo,current.ano].join(' ')],['RUT',current.rut,'Patente',current.patente],['Teléfono',current.telefono,'Kilometraje',current.km],['Correo',current.email,'VIN',current.vin]];for(const row of pairs){const a=wrap(row[0]+': '+(row[1]||'-'),15,83),b=wrap(row[2]+': '+(row[3]||'-'),109,84),h=Math.max(a.length,b.length)*4.4+3;ensure(h);doc.text(a,15,y);doc.text(b,109,y);y+=h}y+=3;section('DETALLE DE COTIZACIÓN');const tableHeader=()=>{doc.setFillColor(24,26,30);doc.rect(14,y-4,182,10,'F');doc.setTextColor(255);doc.setFont('helvetica','bold');doc.setFontSize(8);doc.text('TIPO / CATEGORÍA',16,y+2);doc.text('DESCRIPCIÓN',64,y+2);doc.text('CANT.',148,y+2,{align:'right'});doc.text('UNIT.',173,y+2,{align:'right'});doc.text('NETO',194,y+2,{align:'right'});y+=12};tableHeader();let neto=0;for(const it of current.items){const subtotal=(Number(it.cant)||0)*(Number(it.unit)||0);neto+=subtotal;const label=it.tipo+(it.tipo==='Repuesto'?' · '+(it.categoria||'Original'):'');const lines1=wrap(label,16,45),lines2=wrap(it.desc,64,64);const h=Math.max(lines1.length,lines2.length)*4.3+5;ensure(h+3);if(y===49)tableHeader();doc.setFontSize(8);doc.setTextColor(25);doc.text(lines1,16,y);doc.text(lines2,64,y);tx(it.cant,148,y,8,false,'right');tx(money(it.unit),173,y,8,false,'right');tx(money(subtotal),194,y,8,false,'right');y+=h;doc.setDrawColor(225);doc.line(14,y-3,196,y-3)}ensure(37);y+=7;tx('NETO',150,y,10,true,'right');tx(money(neto),196,y,10,true,'right');y+=8;tx('IVA 19%',150,y,10,true,'right');tx(money(Math.round(neto*.19)),196,y,10,true,'right');y+=9;doc.setDrawColor(205,24,34);doc.line(125,y-5,196,y-5);tx('TOTAL',150,y,13,true,'right');tx(money(neto+Math.round(neto*.19)),196,y,13,true,'right');y+=13;
for(const [title,value] of [['CONDICIONES',current.condiciones],['OBSERVACIONES',current.notas]]){if(!value)continue;section(title);const lines=wrap(value,15,180);for(let i=0;i<lines.length;i+=12){const part=lines.slice(i,i+12);ensure(part.length*4.5+3);doc.text(part,15,y);y+=part.length*4.5+4}}
const count=doc.internal.getNumberOfPages();for(let p=1;p<=count;p++){doc.setPage(p);doc.setDrawColor(210);doc.line(14,281,196,281);tx('CERO FALLA  |  +56 9 6925 1525',14,287,8);tx(p+' / '+count,196,287,8,false,'right')}return doc}
$('#pdf').onclick=()=>{try{pdf().save(current.numero+'.pdf')}catch(e){alert('Error al generar PDF: '+e.message)}};
$('#enviar').onclick=async()=>{try{const doc=pdf(),file=new File([doc.output('blob')],current.numero+'.pdf',{type:'application/pdf'});if(navigator.canShare?.({files:[file]})&&navigator.share){await navigator.share({files:[file],title:'Cotización CERO FALLA '+current.numero,text:'Adjunto cotización CERO FALLA.'})}else{doc.save(current.numero+'.pdf');alert('El navegador no admite compartir el PDF directamente. Se descargó el documento.')}}catch(e){if(e.name!=='AbortError')alert('No fue posible compartir: '+e.message)}};
const prev=Object.values(all()).at(-1);load(prev||fresh());save();
